---
- name: Configure webserver with nginx
  hosts: test
  become: true
  tasks:
  - name: Update repo
    command: yum update -y

  - name: Install nginx
    yum:
      name: nginx
      state: latest
      update_cache: yes
