---
- name: Configure webserver with nginx
  hosts: test
  become: true
  tasks:
  - name: install EPEL repo
    yum: 
      name: epel-release 
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: latest
      update_cache: yes
